# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pool:
  vmImage: ubuntu-latest
jobs:
 - job: job1
   dependsOn: job2
   steps:
    - script: echo hello world job1
      displayName: 'run a one line script for job1'
 - job: job2
   steps:
    - script: echo hello world job2
      displayName: 'run a one line script for job2'
 - job: job3
   dependsOn: job1
   steps:
    - script: echo hello world job3
      displayName: 'run a one line script for job3'
